### ISSUE TITLE
Error reproducing examples

### ISSUE THREAD

**Issue by nquesada** [MotohisaFukuda/RTNI#1]
When I run 
```python
from IHU_source import *

e1 = [["U", 1, "out", 1], ["X", 1, "in", 1]]
e2 = [["Y", 1, "out", 1], ["U", 1, "in", 1]]
e3 = [["U*", 1, "out", 1], ["Y", 1,"in", 1]]
g = [e1, e2, e3]
gw = [g,1]

d = symbols('d')
Eg = integrateHaarUnitary(gw, ["U", [d], [d], d])
print(Eg)
visualizeTN(Eg)
```
I get
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_47379/1969515732.py in <module>
      8 
      9 d = symbols('d')
---> 10 Eg = integrateHaarUnitary(gw, ["U", [d], [d], d])
     11 print(Eg)
     12 visualizeTN(Eg)

~/Code/RTNI/PYTHON/IHU_source.py in integrateHaarUnitary(EWs, RM_List)
    359     Collections = []
    360     for x in EWs_p:
--> 361         Collections += Calc(x[0],x[1],RM_List).Output
    362     Collections_List = [ [list(c[0].edges()), c[1]] for c in Collections]
    363     #print("Collections_List",Collections_List)

~/Code/RTNI/PYTHON/IHU_source.py in __init__(self, Edges, Weight, RM_List)
    146         self.PRE = Prep(Edges,Weight,RM_List)
    147         SDs = [[len(self.PRE.RM1_grouped[i]),self.RM_List[i][3]] for i in range(self.PRE.RM_Number)]
--> 148         self.WGF_all = WGF(SDs)
    149         self.Output = self.Calculator()
    150 

~/Code/RTNI/PYTHON/IHU_source.py in __init__(self, SDs)
    129             else:
    130                 with open('Weingarten/functions{}.pkl'.format(Sizes[i]), 'rb') as file:
--> 131                     Photocopy = pickle.load(file)# Unpickling
    132             self.Dic['wg{}'.format(Sizes[i])] = [[p[0],p[1].subs(n,Dims[i])] for p in Photocopy]
    133             # Here, substituting n by t the actual size of matrix.

AttributeError: 'Symbol' object has no attribute '__dict__'
```

These are the versions of the libraries I am using:

![image](https://user-images.githubusercontent.com/991946/183154080-8a80d669-9098-42b1-a779-8641cc5d8a21.png)

Any help on finding out what is going on would be greatly appreciated.

**Comment by MotohisaFukuda** [comment]
I tried the example with the following versions:
sympy                     1.10.1
networkx                  2.8.6

Initially, the codes lead to an error different from the above one. Then, I suspected that it had something to do with pickle a python module. Hence, I tried deleting the following folders:  SGC, SP, and Weingartenm before executing the codes. Fortunately, it worked. Those folders store Weingarten functions and related values for future use. So, for now, please delete those folders before calculations.
Besides, I came to know that pickle is potentially not safe as one can embed malicious codes which are to be executed while being unpickled. Therefore, I plan to modify the program shortly to avoid using the module.
![image](https://user-images.githubusercontent.com/44628367/192083294-87d85269-36b6-4a97-b9cc-e5d315db84d1.png)
